language: cpp
compiler: g++
dist: trusty
sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install qt4-dev-tools qtbase5-dev libxss-dev libmagic-dev qt4-qmake qt5-qmake tree
  
script:
  - git submodule update --init --recursive
  - export CWD=`pwd`
  - mkdir $CWD/qt5
  - cd $CWD/qt5
  - qmake -qt=qt5 CONFIG+=release PREFIX=/usr CONFIG+=with_power ..
  - make
  - make INSTALL_ROOT=`pwd`/pkg install
  - tree pkg
  - cd $CWD
  - mkdir $CWD/qt4
  - cd $CWD/qt4
  - qmake -qt=qt4 CONFIG+=release PREFIX=/usr CONFIG+=with_power ..
  - make
  - make INSTALL_ROOT=`pwd`/pkg install
  - tree pkg
  - cd $CWD
